import os
# Membaca file hello.txt dengan fungsi read()
exact_path = os.path.dirname(os.path.abspath(__file__))
print(">>> Membaca file hello.txt dengan fungsi read()")
file = open(exact_path + "\hello.txt", "r")
content = file.read()
file.close()
print(content)
# Membaca file hello.txt dengan fungsi readline()
print(">>> Membaca file hello.txt dengan fungsi readline()")
file = open(exact_path + "\hello.txt", "r")
first_line = file.readline()
second_line = file.readline()
file.close()
print(first_line)
print(second_line)